/**
 * PM Inspection — Form Layout
 *
 * Single source of truth for the Packing Material Inspection Record form.
 * Used by:
 *   - /pm-inspection/create  (data entry)
 *   - /pm-inspection/[id]    (view/print)  ← future
 *   - PDF/Excel export       ← future
 *
 * If the QC team adds/removes/renames a field, only this file changes.
 */

import type { PMInwardRow } from './api/pm-inspection'

// ── Header / form metadata (printed in the top-right block) ───────────
export const FORM_META = {
  title: 'Candor Foods Private Limited',
  subtitle: 'Packing Material Inspection Record',
  formCode: 'CFPLB.C5.F.33',
  issueDate: '13/03/2024',
  issueNo: '02',
  revisionDate: '05/01/2026',
  revisionNo: '01',
} as const

// ── Top section: header field grid (Sr. No., dates, supplier, etc.) ───
export type HeaderFieldType = 'text' | 'date' | 'yesno' | 'number'

export interface HeaderFieldDef {
  key: string
  label: string
  type: HeaderFieldType
  /**
   * Where the value originates:
   *   - 'auto'   → generated by the system (e.g. Sr. No. from a sequence)
   *   - 'grn'    → auto-filled from the GRN row passed via sessionStorage
   *   - undefined → manually entered by the inspector
   */
  source?: 'auto' | 'grn'
  /** When source = 'grn', which key on PMInwardRow to copy from. */
  grnField?: keyof PMInwardRow
  required?: boolean
  /** Render full-width on the form (spans 2 grid columns). */
  fullWidth?: boolean
}

export const HEADER_FIELDS: HeaderFieldDef[] = [
  { key: 'sr_no',                label: 'Sr. No.',                       type: 'text',   source: 'auto', required: true },
  { key: 'received_date',        label: 'Received Date',                 type: 'date',   source: 'grn', grnField: 'entry_date', required: true },
  { key: 'inspection_date',      label: 'Inspection Date',               type: 'date',   required: true },
  { key: 'material_description', label: 'Material Description (RM/PM)',  type: 'text',   source: 'grn', grnField: 'items', required: true, fullWidth: true },
  { key: 'challan_no',           label: 'Challan No.',                   type: 'text',   source: 'grn', grnField: 'challan_number' },
  { key: 'invoice_no',           label: 'Invoice No.',                   type: 'text',   source: 'grn', grnField: 'invoice_number' },
  { key: 'supplier_name',        label: 'Supplier Name',                 type: 'text',   source: 'grn', grnField: 'vendor_supplier_name', required: true, fullWidth: true },
  { key: 'vehicle_no',           label: 'Vehicle No.',                   type: 'text',   source: 'grn', grnField: 'vehicle_number' },
  { key: 'coa_received',         label: 'COA Received (Yes/No)',         type: 'yesno' },
  { key: 'quantity',             label: 'Quantity (Nos/Pieces)',         type: 'number', source: 'grn', grnField: 'total_quantity' },
]

// ── Inspection parameter rows (3 columns: Parameter | Observation | Status) ───
export interface ParamRowDef {
  key: string
  parameter: string
  observationPlaceholder?: string
  statusPlaceholder?: string
}

export const VISUAL_VERIFICATION_PARAMS: ParamRowDef[] = [
  {
    key: 'pre_printing_quality',
    parameter: 'Pre-Printing Details & Quality',
    observationPlaceholder: 'e.g. As per the req.',
    statusPlaceholder: 'Complies / Does Not Comply / NA',
  },
  {
    key: 'roll_box_conditions',
    parameter: 'Roll/ Box Conditions',
    observationPlaceholder: 'e.g. OK',
    statusPlaceholder: 'Complies / Does Not Comply / NA',
  },
]

export const INSPECTION_PARAMS: ParamRowDef[] = [
  {
    key: 'dimensions',
    parameter: 'Dimensions (Height & Width)',
    observationPlaceholder: 'e.g. As per the approved req.',
    statusPlaceholder: 'e.g. 205*150*mm (L*W) +/- 1 MM',
  },
  {
    key: 'k_seal',
    parameter: 'K-seal/Bottom Seal',
    observationPlaceholder: 'e.g. As per the req.',
    statusPlaceholder: 'e.g. NA',
  },
  {
    key: 'gsm_weight',
    parameter: 'GSM / Weight',
    observationPlaceholder: 'e.g. As per the req.',
    statusPlaceholder: 'e.g. 84.52 (+-5)/ 6.85 GM +/-5',
  },
  {
    key: 'damage_signs',
    parameter: 'Any Damage/Chemical Spill/Infestation Signs',
    observationPlaceholder: 'e.g. No',
    statusPlaceholder: 'e.g. No',
  },
]

// ── Bottom section ────────────────────────────────────────────────────
export interface FooterFieldDef {
  key: 'remarks' | 'done_by' | 'verified_by'
  label: string
  type: 'text' | 'textarea'
}

export const FOOTER_FIELDS: FooterFieldDef[] = [
  { key: 'remarks',     label: 'Remarks',     type: 'textarea' },
  { key: 'done_by',     label: 'Done By',     type: 'text' },
  { key: 'verified_by', label: 'Verified By', type: 'text' },
]

// ── Common dropdown options ───────────────────────────────────────────
export const STATUS_SUGGESTIONS = ['Complies', 'Does Not Comply', 'NA'] as const
export const YES_NO_OPTIONS = ['yes', 'no'] as const

// ── Form data shape (what the create page builds & POSTs) ─────────────
export interface ParamObservation {
  observation: string
  status: string
}

export interface PMInspectionFormData {
  // Source GRN reference (frozen at creation time)
  company: string
  transaction_no: string
  grn_number: string

  // Header
  sr_no: string
  received_date: string
  inspection_date: string
  material_description: string
  challan_no: string
  invoice_no: string
  supplier_name: string
  vehicle_no: string
  coa_received: 'yes' | 'no' | ''
  quantity: string

  // Visual Verification — keyed by ParamRowDef.key
  visual_verification: Record<string, ParamObservation>
  // Inspection Parameters — keyed by ParamRowDef.key
  inspection_parameters: Record<string, ParamObservation>

  // Footer
  remarks: string
  done_by: string
  verified_by: string
}

// ── Helpers ───────────────────────────────────────────────────────────
export function emptyParamMap(defs: ParamRowDef[]): Record<string, ParamObservation> {
  return Object.fromEntries(defs.map((d) => [d.key, { observation: '', status: '' }]))
}

export function buildEmptyForm(grn?: PMInwardRow | null): PMInspectionFormData {
  const today = new Date().toISOString().slice(0, 10)
  const f: PMInspectionFormData = {
    company: grn?.company || '',
    transaction_no: grn?.transaction_no || '',
    grn_number: grn?.grn_number || '',
    sr_no: '',
    received_date: '',
    inspection_date: today,
    material_description: '',
    challan_no: '',
    invoice_no: '',
    supplier_name: '',
    vehicle_no: '',
    coa_received: '',
    quantity: '',
    visual_verification: emptyParamMap(VISUAL_VERIFICATION_PARAMS),
    inspection_parameters: emptyParamMap(INSPECTION_PARAMS),
    remarks: '',
    done_by: '',
    verified_by: '',
  }

  if (grn) {
    for (const def of HEADER_FIELDS) {
      if (def.source !== 'grn' || !def.grnField) continue
      const raw = (grn as any)[def.grnField]
      if (raw == null) continue
      ;(f as any)[def.key] = String(raw)
    }
  }

  return f
}

// sessionStorage key for handing the GRN row from the list page → create page
export const PM_GRN_SESSION_KEY = 'pm-inspection-grn-row'
