// frontend/src/config/doc-forms.ts

export interface DocFormConfig {
  formType: string
  label: string
  docNo: string
  dateField: string | null
  listColumns: string[]
  routeSlug: string
}

export const DOC_FORMS: Record<string, DocFormConfig> = {
  // ── Batch 1 (22) ──
  productweightcheck:        { formType: "productweightcheck",        routeSlug: "productweightcheck",        label: "Product Weight & Sealing Check",   docNo: "CFPLA.C6.F.16",  dateField: "check_date",      listColumns: ["check_date", "product_name", "batch_no", "customer", "warehouse"] },
  productiontoolissuance:    { formType: "productiontoolissuance",    routeSlug: "productiontoolissuance",    label: "Production Tool Issuance",         docNo: "CFPLA.C4.F.22",  dateField: "check_date",      listColumns: ["check_date", "checked_by", "verified_by", "warehouse"] },
  dailycleaningchecklist:    { formType: "dailycleaningchecklist",    routeSlug: "dailycleaningchecklist",    label: "Daily Cleaning Checklist",         docNo: "CFPLA.C4.F.54",  dateField: "month",           listColumns: ["month", "area", "tab_code", "warehouse"] },
  equipmentcleaningsanitation: { formType: "equipmentcleaningsanitation", routeSlug: "equipmentcleaningsanitation", label: "Equipment Cleaning & Sanitation", docNo: "CFPLA.C4.F.19", dateField: "month",          listColumns: ["month", "area", "warehouse"] },
  preproductioninspection:   { formType: "preproductioninspection",   routeSlug: "preproductioninspection",   label: "Pre-Production Inspection",        docNo: "CFPLA.C6.F.07",  dateField: "inspection_date", listColumns: ["inspection_date", "inspection_time", "warehouse"] },
  lineclearancerecord:       { formType: "lineclearancerecord",       routeSlug: "lineclearancerecord",       label: "Line Clearance Record",            docNo: "CFPLA.C5.F.44",  dateField: null,              listColumns: ["area", "warehouse", "created_at"] },
  personalhygienecheckup:    { formType: "personalhygienecheckup",    routeSlug: "personalhygienecheckup",    label: "Personal Hygiene & Health Checkup",docNo: "CFPLA.C7.F.39",  dateField: "check_date",      listColumns: ["check_date", "area", "checked_by", "warehouse"] },
  roastingtemperature:       { formType: "roastingtemperature",       routeSlug: "roastingtemperature",       label: "Roasting Temperature & Time",      docNo: "CFPLA.C2.F.42",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  weighingscalecalibration:  { formType: "weighingscalecalibration",  routeSlug: "weighingscalecalibration",  label: "Weighing Scale Calibration",       docNo: "CFPLA.C6.F.41",  dateField: "inspection_date", listColumns: ["inspection_date", "calibrated_by", "verified_by", "warehouse"] },
  "water-analysis":          { formType: "water-analysis",            routeSlug: "water-analysis",            label: "Water Analysis Record",            docNo: "CFPLA.C4.F.04",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "incident-report":         { formType: "incident-report",           routeSlug: "incident-report",           label: "Food Safety Incident Report",      docNo: "CFPLA.C5.F.05",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "safety-meeting":          { formType: "safety-meeting",            routeSlug: "safety-meeting",            label: "Food Safety Meeting Minutes",      docNo: "CFPLA.C.F.09",   dateField: "meeting_date",    listColumns: ["meeting_date", "venue", "warehouse"] },
  "new-product-verification":{ formType: "new-product-verification",  routeSlug: "new-product-verification",  label: "New Product Verification",         docNo: "CFPLA.C5.F.13",  dateField: "verify_date",     listColumns: ["verify_date", "product_name", "customer_name", "warehouse"] },
  "mock-drill":              { formType: "mock-drill",                routeSlug: "mock-drill",                label: "Emergency Mock Drill",             docNo: "CFPLA.C4.F.14",  dateField: "drill_datetime",  listColumns: ["drill_datetime", "location", "warehouse"] },
  "gmp-ghp-inspection":      { formType: "gmp-ghp-inspection",        routeSlug: "gmp-ghp-inspection",        label: "Monthly GMP & GHP Inspection",     docNo: "CFPLA.C3.F.15",  dateField: "audit_datetime",  listColumns: ["audit_datetime", "auditor_name", "rating", "percentage", "warehouse"] },
  "temperature-humidity":    { formType: "temperature-humidity",      routeSlug: "temperature-humidity",      label: "Temperature & Humidity Record",    docNo: "CFPLA.C6.F.17",  dateField: "month",           listColumns: ["month", "area", "checked_by", "warehouse"] },
  "inprocess-qc-record":     { formType: "inprocess-qc-record",       routeSlug: "inprocess-qc-record",       label: "In-process Quality Check",         docNo: "CFPLA.C6.F.18",  dateField: "check_date",      listColumns: ["check_date", "warehouse", "created_by"] },
  "gmp-schedule":            { formType: "gmp-schedule",              routeSlug: "gmp-schedule",              label: "Monthly GMP Schedule",             docNo: "CFPLA.C3.F.23",  dateField: "year",            listColumns: ["year", "warehouse", "created_by"] },
  "inward-rm-check":         { formType: "inward-rm-check",           routeSlug: "inward-rm-check",           label: "Inward Raw Material Check",        docNo: "CFPLA.C5.F.25",  dateField: "month",           listColumns: ["month", "area", "warehouse"] },
  "fg-chemical-analysis":    { formType: "fg-chemical-analysis",      routeSlug: "fg-chemical-analysis",      label: "Finished Good Chemical Analysis",  docNo: "CFPLA.C5.F.26",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "eyewash-refill":          { formType: "eyewash-refill",            routeSlug: "eyewash-refill",            label: "Eye Wash Bottle Refilling",        docNo: "CFPLA.C7.F.27",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "first-aid-box":           { formType: "first-aid-box",             routeSlug: "first-aid-box",             label: "First Aid Box Record",             docNo: "CFPLA.C7.F.29",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  // ── Batch 2 (15) ──
  "traceability":            { formType: "traceability",              routeSlug: "traceability",              label: "Traceability Report",              docNo: "CFPLA.C3.F.30",  dateField: "report_date",     listColumns: ["report_date", "product_name", "batch_number", "warehouse"] },
  "lux-monitoring":          { formType: "lux-monitoring",            routeSlug: "lux-monitoring",            label: "Lux Monitoring Record",            docNo: "CFPLA.C4.F.32",  dateField: "check_date",      listColumns: ["check_date", "checked_by", "warehouse"] },
  "pre-weighing":            { formType: "pre-weighing",              routeSlug: "pre-weighing",              label: "Pre Weighing Check Record",        docNo: "CFPLA.C6.F.34",  dateField: "check_date",      listColumns: ["check_date", "customer", "product", "warehouse"] },
  "fly-catcher":             { formType: "fly-catcher",               routeSlug: "fly-catcher",               label: "Daily Fly Catcher Check",          docNo: "CFPLA.C7.F.37",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "ccp-roasting-bar":        { formType: "ccp-roasting-bar",          routeSlug: "ccp-roasting-bar",          label: "CCP Roasting (Bar Line)",          docNo: "CFPLA.C2.F.43",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "vehicle-inspection":      { formType: "vehicle-inspection",        routeSlug: "vehicle-inspection",        label: "Incoming Vehicle Inspection",      docNo: "CFPLA.C3.F.45",  dateField: "inspection_date", listColumns: ["inspection_date", "vendor_name", "vehicle_number", "warehouse"] },
  "outgoing-vehicle-inspection": { formType: "outgoing-vehicle-inspection", routeSlug: "outgoing-vehicle-inspection", label: "Outgoing Vehicle Inspection", docNo: "CFPLA.C5.F.46", dateField: "dispatch_date",  listColumns: ["dispatch_date", "customer_name", "vehicle_number", "warehouse"] },
  "glass-brittle-check":     { formType: "glass-brittle-check",       routeSlug: "glass-brittle-check",       label: "Glass & Brittle Check Record",     docNo: "CFPLA.C4.F.48",  dateField: "year",            listColumns: ["year", "warehouse", "created_by"] },
  "preventive-maintenance":  { formType: "preventive-maintenance",    routeSlug: "preventive-maintenance",    label: "Preventive Maintenance Checklist", docNo: "CFPLA.C4.F.50a", dateField: "month",           listColumns: ["month", "checked_by", "warehouse"] },
  "new-equipment-clearance": { formType: "new-equipment-clearance",   routeSlug: "new-equipment-clearance",   label: "New Equipment Clearance",          docNo: "CFPLA.C4.F.51",  dateField: "commissioning_date", listColumns: ["commissioning_date", "equipment_name", "warehouse"] },
  "waste-disposal":          { formType: "waste-disposal",            routeSlug: "waste-disposal",            label: "Waste Disposal Record",            docNo: "CFPLA.C4.F.52",  dateField: "month",           listColumns: ["month", "area", "warehouse"] },
  "chemical-preparation":    { formType: "chemical-preparation",      routeSlug: "chemical-preparation",      label: "Chemical Preparation Record",      docNo: "CFPLA.C4.F.53",  dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "deep-cleaning":           { formType: "deep-cleaning",             routeSlug: "deep-cleaning",             label: "Deep Cleaning Record",             docNo: "CFPLA.C4.F.55",  dateField: "month",           listColumns: ["month", "checked_by", "warehouse"] },
  "non-conforming-product":  { formType: "non-conforming-product",    routeSlug: "non-conforming-product",    label: "Non Conforming Product Report",    docNo: "CFPLA.C5.F.57",  dateField: null,              listColumns: ["non_conformity_no", "supplier", "detected_by", "warehouse"] },
  "rework-recycling":        { formType: "rework-recycling",          routeSlug: "rework-recycling",          label: "Re-Work / Re-Cycling / Re-Packing",docNo: "CFPLA.C5.F.58", dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  // ── Training (5) ──
  "training-attendance":     { formType: "training-attendance",       routeSlug: "training/attendance-sheet",  label: "Training Attendance Sheet",        docNo: "CFPLA.C7.F.03",  dateField: "training_date",   listColumns: ["training_date", "conducted_by", "department", "warehouse"] },
  "training-attendance-workers": { formType: "training-attendance-workers", routeSlug: "training/attendance-workers", label: "Training Attendance (Workers)", docNo: "CFPLA.C7.F.03", dateField: null,            listColumns: ["warehouse", "created_at", "created_by"] },
  "training-reference-sheet":{ formType: "training-reference-sheet",  routeSlug: "training/reference-sheet",  label: "Reference Material Sheet",         docNo: "CFPLA.C7.F.03i", dateField: null,              listColumns: ["warehouse", "created_at", "created_by"] },
  "training-feedback":       { formType: "training-feedback",         routeSlug: "training/feedback",         label: "Trainee & Trainer Feedback",       docNo: "CFPLA.C7.F.03j", dateField: "feedback_date",   listColumns: ["feedback_date", "participant_name", "training_program", "warehouse"] },
  "training-card":           { formType: "training-card",             routeSlug: "training/training-card",    label: "Employee Training Card",           docNo: "CFPLA.C7.F.03k", dateField: null,              listColumns: ["employee_name", "designation", "warehouse"] },
}
